### ISSUE TITLE
Draw boss locations on dungeon maps

### ISSUE THREAD

**Issue by miketrethewey** [x10power/ffmq-rando-tracker#7]
- [ ] Level Forest - Minotaur
- [ ] Bone Dungeon - Flamerus Rex #12
- [ ] Wintry Cave - Squidite
- [ ] Falls Basin - Snow Crab
- [ ] Ice Pyramid -  Ice Golem #13
- [ ] Mine - Jinn
- [ ] Volcano - Medusa
- [ ] Lava Dome - Dualhead Hydra #11
- [ ] Giant Tree - Gidrah
- [ ] Mount Gale - Dullahan
- [ ] Pazuzu's Tower - Pazuzu
- [ ] Doom Castle
  - [ ] Skullrus Rex
  - [ ] Stone Golem
  - [ ] Twinhead Wyvern
  - [ ] Zuh
  - [ ] Dark King
